/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://bhxlremg5zfuleafoxfiqxqwou.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cy5ttm756vamjlmfkqb5bnwhz4",
    "aws_cognito_identity_pool_id": "us-east-2:757861ed-6787-44dd-a92a-7cb1aa2fef15",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rPCaOAyHy",
    "aws_user_pools_web_client_id": "2fbaik90c22a29oflrt7a44kuk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
