projects:
  ImageSearchAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: zf5qnuhb5fh6flerqercdjpx4m
        maxDepth: 2
